# Generated by Django 5.2.4 on 2025-07-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_type', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100)),
                ('job_number', models.CharField(max_length=100)),
                ('start_job', models.CharField(max_length=100)),
                ('partition_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alerts_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
